org: jiahng
app: carousell-discord-scraper
service: CarousellDiscordScraper
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: !Ref CommandTopic
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
          Resource: !GetAtt RequestTable.Arn

package:
  individually: true

functions:
  proxyLambda:
    handler: proxylambda/index.handler
    environment:
      TOPIC_ARN: !Ref CommandTopic
    package:
      patterns:
        - '!./**'
        - proxylambda/**
  startHandler:
    handler: starthandler/index.handler
    environment:
      TABLE_ARN: !Ref RequestTable
    events:
      - sns:
          arn: !Ref CommandTopic
          topicName: CommandTopic
          filterPolicy:
            command:
              - start
    package:
      patterns:
        - '!./**'
        - starthandler/**
        - handlerpackage/**
  statusHandler:
    handler: statushandler/index.handler
    environment:
      TABLE_ARN: !Ref RequestTable
    events:
      - sns:
          arn: !Ref CommandTopic
          topicName: CommandTopic
          filterPolicy:
            command:
              - status
    package:
      patterns:
        - '!./**'
        - statushandler/**
        - handlerpackage/**
  stopHandler:
    handler: stophandler/index.handler
    environment:
      TABLE_ARN: !Ref RequestTable
    events:
      - sns:
          arn: !Ref CommandTopic
          topicName: CommandTopic
          filterPolicy:
            command:
              - stop
    package:
      patterns:
        - '!./**'
        - stophandler/**
        - handlerpackage/**

resources:
  Resources:
    CommandTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CarousellDiscordScraperCommandTopic
    ProxyLambdaInvoker:
      Type: AWS::IAM::User
      Properties:
        UserName: "ProxyLambdaInvoker"
        Policies:
        - PolicyName: ProxyLambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - "lambda:InvokeFunction"
              Resource: !GetAtt ProxyLambdaLambdaFunction.Arn #{ "Fn::GetAtt": ["ProxyLambdaLambdaFunction", "Arn" ] }
    ProxyLambdaInvokerUserKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName:
          Ref: ProxyLambdaInvoker
    RequestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CarousellDiscordScraperRequestTable
        AttributeDefinitions:
          - AttributeName: channel_id
            AttributeType: S
        KeySchema:
          - AttributeName: channel_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        
outputs:
  ProxyLambdaInvokerAccessKeyID: !Ref ProxyLambdaInvokerUserKey
  ProxyLambdaInvokerSecretAccessKey: !GetAtt ProxyLambdaInvokerUserKey.SecretAccessKey
  ProxyLambdaArn: !GetAtt ProxyLambdaLambdaFunction.Arn



