org: jiahng
app: carousell-discord-scraper
service: CarousellDiscordScraper
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: !Ref CommandTopic
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource:
            - !GetAtt RequestTable.Arn
            - !GetAtt ListingTable.Arn
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

package:
  individually: true

functions:
  proxyLambda:
    handler: proxylambda/index.handler
    environment:
      TOPIC_ARN: !Ref CommandTopic
    package:
      patterns:
        - "!./**"
        - proxylambda/**

  startHandler:
    handler: starthandler/index.handler
    environment:
      TABLE_ARN: !Ref RequestTable
    package:
      patterns:
        - "!./**"
        - starthandler/**
        - handlerpackage/**
    events:
      - sns:
          arn: !Ref CommandTopic
          topicName: CommandTopic
          filterPolicy:
            command:
              - start

  statusHandler:
    handler: statushandler/index.handler
    environment:
      TABLE_ARN: !Ref RequestTable
    package:
      patterns:
        - "!./**"
        - statushandler/**
        - handlerpackage/**
    events:
      - sns:
          arn: !Ref CommandTopic
          topicName: CommandTopic
          filterPolicy:
            command:
              - status

  stopHandler:
    handler: stophandler/index.handler
    environment:
      TABLE_ARN: !Ref RequestTable
    package:
      patterns:
        - "!./**"
        - stophandler/**
        - handlerpackage/**
    events:
      - sns:
          arn: !Ref CommandTopic
          topicName: CommandTopic
          filterPolicy:
            command:
              - stop

  idScraperLambda:
    handler: idscraperlambda/index.handler
    environment:
      LISTING_TABLE_ARN: !Ref ListingTable
    package:
      patterns:
        - "!./**"
        - idscraperlambda/**

  scraperProxy:
    handler: scraperproxy/index.handler
    environment:
      TABLE_ARN: !Ref RequestTable
      SCRAPER_FN: !GetAtt IdScraperLambdaLambdaFunction.Arn
    package:
      patterns:
        - "!./**"
        - scraperproxy/**
    # events:
    #   - schedule: rate(5 minutes)

resources:
  Resources:
    CommandTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CarousellDiscordScraperCommandTopic

    ProxyLambdaInvoker:
      Type: AWS::IAM::User
      Properties:
        UserName: "ProxyLambdaInvoker"
        Policies:
          - PolicyName: ProxyLambdaInvokePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "lambda:InvokeFunction"
                  Resource: !GetAtt ProxyLambdaLambdaFunction.Arn

    ProxyLambdaInvokerUserKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName:
          Ref: ProxyLambdaInvoker

    RequestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CarousellDiscordScraperRequestTable
        AttributeDefinitions:
          - AttributeName: channel_id
            AttributeType: S
        KeySchema:
          - AttributeName: channel_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ListingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CarousellDiscordScraperListingTable
        AttributeDefinitions:
          - AttributeName: channel_id
            AttributeType: S
          - AttributeName: listing_id
            AttributeType: S
        KeySchema:
          - AttributeName: channel_id
            KeyType: HASH
          - AttributeName: listing_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

outputs:
  ProxyLambdaInvokerAccessKeyID: !Ref ProxyLambdaInvokerUserKey
  ProxyLambdaInvokerSecretAccessKey: !GetAtt ProxyLambdaInvokerUserKey.SecretAccessKey
  ProxyLambdaArn: !GetAtt ProxyLambdaLambdaFunction.Arn
